spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: iryna
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8888

taco:
  orders:
    pageSize: 20

---
spring:
  config:
    activate:
      on-profile: test

server:
  port: 0

taco:
  orders:
    pageSize: 20

